# Generated by Django 4.2.1 on 2023-07-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapapp', '0004_author_contact_post_tag_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
