# Generated by Django 4.2.1 on 2023-07-11 20:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapapp', '0005_remove_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=150)),
                ('excerpt1', models.CharField(max_length=200)),
                ('image_name1', models.CharField(max_length=100)),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('slug1', models.SlugField(unique=True)),
                ('content1', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('author1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='dapapp.author')),
            ],
        ),
    ]
