# Generated by Django 4.2.1 on 2023-07-12 01:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapapp', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=150)),
                ('excerpt2', models.CharField(max_length=200)),
                ('image_name2', models.CharField(max_length=100)),
                ('date2', models.DateTimeField(auto_now_add=True)),
                ('slug2', models.SlugField(unique=True)),
                ('content2', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('author2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='dapapp.author')),
            ],
        ),
    ]
